### ISSUE TITLE
[Dúvida] Tópico 24

### ISSUE THREAD

**Issue by ianitow** [plinioleitao/sgbd-2024-1-bcc#24]
Boa noite, prof. Plínio.

Percebi que a solução do exercício 2 do tópico 24 não está no github, precisava corrigir com minhas respostas.

https://github.com/plinioleitao/sgbd-2024-1-bcc/blob/main/topico/topico-24solucao-02.md (NOT FOUND)

**Comment by plinioleitao** [comment]
Olá Iaan,

Postei no ambiente virtual a solução do exercício que você solicitou.

Grato,


Plinio Sa Leitao-Junior, PhD.
Full Professor at the Institute of Informatics (INF)
Federal University of Goias (UFG) - Brazil


Em ter., 23 de jul. de 2024 às 21:37, Iaan Mesquita de Souza <
***@***.***> escreveu:

**Comment by ianitow** [comment]
Muito obrigado, professor.
